name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "fix: <Please write a comprehensive title after the 'fix: ' prefix>"
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to report an issue. Please fill the form below.
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please confirm and check all the following options.
      options:
        - label: I added a very descriptive title to this issue.
          required: true
        - label: I used the GitHub search to find a similar question and didn't find it.
          required: true
        - label: I am sure that this is a bug in Meteors rather than my code.
          required: true
        - label: The bug is not resolved by updating to the latest stable version of Meteors.
          required: true
        - label: I included a link to the documentation page I am referring to (if applicable).
          required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      placeholder: |
        The following code:

        ```python
        from meteors.foo import foo

        def bad_code(inputs) -> int:
          raise NotImplementedError('For demo purpose')

          chain = foo(bad_code)
          chain.invoke('Hello!')
        ```
    validations:
      required: true
  - type: textarea
    id: error
    validations:
      required: false
    attributes:
      label: Error Message and Stack Trace (if applicable)
      description: |
        If you are reporting an error, please include the full error message and stack trace.
      placeholder: |
        Exception + full stack trace
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What is the impacted environment ?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false
