name: "💡 Feature Request"
description: Create a new ticket for a feature request
title: "feat: <Please provide a clear and concise title>"
body:
  - type: textarea
    id: description
    attributes:
      label: "Feature Description"
      description: Provide a clear and concise description of the feature you're requesting.
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: "Use Case"
      description: Describe the use case or problem this feature would solve.
    validations:
      required: true
  - type: textarea
    id: reference_issues
    attributes:
      label: "Reference Issues"
      description: If there are any related issues, reference them here (e.g., "Closes #123", "Relates to #456").
      placeholder: "#Issues IDs"
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: Add any other context, examples, or references that would help clarify the feature request.
    validations:
      required: false
